python3.6 -m pip install setuptools
python3.6 -m pip install requests
python3.6 -m pip install requests[security]
python3.6 -m pip install requests-cache
python3.6 -m pip install babelfish
python3.6 -m pip install "guessit<2"
python3.6 -m pip install "subliminal<2"
python3.6 -m pip install stevedore==1.19.1
python3.6 -m pip install python3.6-dateutil
python3.6 -m pip install deluge-client
python3.6 -m pip install qtfaststart
